export interface Project {
    id: string;
    category: 'residential' | 'commercial' | 'interior' | 'hospitality';
    title: string;
    subtitle?: string;
    location: string;
    year: string;
    services: string[];
    coverImage: string;
    images: string[];
    featured?: boolean;
}

export const projects: Project[] = [
    // EXTERIOR FACADES
    {
        id: 'facade-1',
        category: 'residential',
        title: 'Maison Blanche',
        subtitle: 'Private Villa',
        location: 'Kuwait City',
        year: '2024',
        services: ['Architecture', 'Facade Design', 'Lighting'],
        coverImage: '/projects/facade-1/1.jpg',
        images: Array.from({ length: 9 }, (_, i) => `/projects/facade-1/${i + 1}.jpg`),
        featured: true,
    },
    {
        id: 'facade-2',
        category: 'residential',
        title: 'Al Salam Residence',
        subtitle: 'Family Home',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Exterior Design'],
        coverImage: '/projects/facade-2/Facade-1_1.jpg',
        images: [
            '/projects/facade-2/Facade-1_1.jpg',
            '/projects/facade-2/Facade-1_2.jpg',
            '/projects/facade-2/Facade-1_3.jpg',
            '/projects/facade-2/Facade-1_4.jpg',
        ],
    },
    {
        id: 'facade-3',
        category: 'residential',
        title: 'Contemporary Villa',
        subtitle: 'Modern Living',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Facade Design'],
        coverImage: '/projects/facade-3/Facade-2_1.jpg',
        images: [
            '/projects/facade-3/Facade-2_1.jpg',
            '/projects/facade-3/Facade-2_2.jpg',
            '/projects/facade-3/Facade-2_3.jpg',
            '/projects/facade-3/Facade-2_4.jpg',
            '/projects/facade-3/Facade-2_5.jpg',
        ],
        featured: true,
    },
    {
        id: 'facade-4',
        category: 'residential',
        title: 'The Atrium House',
        subtitle: 'Luxury Residence',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Landscape', 'Lighting'],
        coverImage: '/projects/facade-4/Facade-3_1.jpg',
        images: [
            '/projects/facade-4/Facade-3_1.jpg',
            '/projects/facade-4/Facade-3_2.jpg',
            '/projects/facade-4/Facade-3_3.jpg',
            '/projects/facade-4/Facade-3_4.jpg',
            '/projects/facade-4/Facade-3_5.jpg',
            '/projects/facade-4/Facade-3_6.jpg',
        ],
    },
    {
        id: 'facade-5',
        category: 'residential',
        title: 'Minimalist Estate',
        subtitle: 'Private Villa',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Interior Coordination'],
        coverImage: '/projects/facade-5/Facade-4_1.jpg',
        images: [
            '/projects/facade-5/Facade-4_1.jpg',
            '/projects/facade-5/Facade-4_2.jpg',
            '/projects/facade-5/Facade-4_3.jpg',
        ],
    },
    {
        id: 'facade-6',
        category: 'residential',
        title: 'Urban Retreat',
        subtitle: 'City Villa',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Facade Design'],
        coverImage: '/projects/facade-6/1.jpg',
        images: Array.from({ length: 5 }, (_, i) => `/projects/facade-6/${i + 1}.jpg`),
    },
    {
        id: 'poolside',
        category: 'residential',
        title: 'Poolside Pavilion',
        subtitle: 'Resort Living',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Pool Design', 'Landscape'],
        coverImage: '/projects/poolside/1.jpg',
        images: Array.from({ length: 12 }, (_, i) => `/projects/poolside/${i + 1}.jpg`),
        featured: true,
    },
    {
        id: 'dana',
        category: 'residential',
        title: 'Dana Residence',
        subtitle: 'Signature Villa',
        location: 'Kuwait',
        year: '2024',
        services: ['Architecture', 'Interior', 'Landscape'],
        coverImage: '/projects/dana/1.jpg',
        images: Array.from({ length: 22 }, (_, i) => `/projects/dana/${i + 1}.jpg`),
        featured: true,
    },
    // INTERIOR PROJECTS
    {
        id: 'hassan-at',
        category: 'interior',
        title: 'Hassan Residence',
        subtitle: 'Luxury Interior',
        location: 'Kuwait',
        year: '2024',
        services: ['Interior Design', 'Custom Furniture', 'Lighting'],
        coverImage: '/projects/hassan-at/Dining_1.jpg',
        images: [
            '/projects/hassan-at/Dining_1.jpg',
            '/projects/hassan-at/Dining_2.jpg',
            '/projects/hassan-at/Dining_3.jpg',
            '/projects/hassan-at/Dining_4.jpg',
            '/projects/hassan-at/Guest Bedroom_1.jpg',
            '/projects/hassan-at/Guest Bedroom_2.jpg',
            '/projects/hassan-at/Guest Bedroom_3.jpg',
            '/projects/hassan-at/Dressing _1.jpg',
            '/projects/hassan-at/Dressing _2.jpg',
        ],
        featured: true,
    },
    {
        id: 'osama',
        category: 'interior',
        title: 'Osama Residence',
        subtitle: 'Contemporary Living',
        location: 'Kuwait',
        year: '2024',
        services: ['Interior Design', 'Pool Design'],
        coverImage: '/projects/osama/Living_1.jpg',
        images: [
            '/projects/osama/Living_1.jpg',
            '/projects/osama/Living_2.jpg',
            '/projects/osama/Living_3.jpg',
            '/projects/osama/Living_4.jpg',
            '/projects/osama/Living_5.jpg',
            '/projects/osama/Living_6.jpg',
            '/projects/osama/Bedroom.jpg',
            '/projects/osama/Bedroom_2.jpg',
            '/projects/osama/Bathroom_1.jpg',
            '/projects/osama/Pool_1.jpg',
            '/projects/osama/Pool_2.jpg',
            '/projects/osama/Pool_3.jpg',
            '/projects/osama/Pool_4.jpg',
        ],
        featured: true,
    },
    {
        id: 'amal-su',
        category: 'interior',
        title: 'Amal Residence',
        subtitle: 'Elegant Interiors',
        location: 'Kuwait',
        year: '2024',
        services: ['Interior Design', 'Furniture Selection'],
        coverImage: '/projects/amal-su/Living_1.jpg',
        images: [
            '/projects/amal-su/Living_1.jpg',
            '/projects/amal-su/Living_2.jpg',
            '/projects/amal-su/Living_3.jpg',
            '/projects/amal-su/Living_4.jpg',
            '/projects/amal-su/Living_5.jpg',
            '/projects/amal-su/Reception_1.jpg',
            '/projects/amal-su/Reception_2.jpg',
            '/projects/amal-su/Reception_3.jpg',
            '/projects/amal-su/Kitchen_3.jpg',
            '/projects/amal-su/Kitchen_4.jpg',
        ],
    },
    {
        id: 'abdullah',
        category: 'interior',
        title: 'Abdullah Residence',
        subtitle: 'Family Home Interior',
        location: 'Kuwait',
        year: '2024',
        services: ['Interior Design', 'Custom Millwork'],
        coverImage: '/projects/abdullah/1.jpg',
        images: Array.from({ length: 32 }, (_, i) => `/projects/abdullah/${i + 1}.jpg`),
    },
    {
        id: 'rawan-tr',
        category: 'interior',
        title: 'Rawan Residence',
        subtitle: 'Modern Interior',
        location: 'Kuwait',
        year: '2024',
        services: ['Interior Design', 'Lighting Design'],
        coverImage: '/projects/rawan-tr/1.jpg',
        images: Array.from({ length: 14 }, (_, i) => `/projects/rawan-tr/${i + 1}.jpg`),
    },
];

export const getFeaturedProjects = () => projects.filter(p => p.featured);
export const getProjectsByCategory = (category: Project['category']) =>
    projects.filter(p => p.category === category);
export const getProjectById = (id: string) => projects.find(p => p.id === id);
